"""add_notes_to_bookings

Revision ID: ac8b440e58b0
Revises: c796a5e365dc
Create Date: 2026-05-17 18:13:54.695191

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac8b440e58b0"
down_revision: str | Sequence[str] | None = "c796a5e365dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("Notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "Notes")
    # ### end Alembic commands ###
