"""add_notes_to_bookings

Revision ID: ac8b440e58b0
Revises: c796a5e365dc
Create Date: 2026-05-17 18:13:54.695191

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac8b440e58b0"
down_revision: Union[str, Sequence[str], None] = "c796a5e365dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("Notes", sa.Text(), nullable=True))
    op.alter_column(
        "bookings", "Nombre,Apellidos", existing_type=mysql.VARCHAR(length=100), nullable=True
    )
    op.drop_index(op.f("ID"), table_name="bookings")
    op.drop_constraint(op.f("fk_bookings_Apartamentos_Booking_ID"), "bookings", type_="foreignkey")
    op.drop_column("bookings", "Electric Allowance")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column(
            "Electric Allowance",
            mysql.SMALLINT(),
            server_default=sa.text("'0'"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_bookings_Apartamentos_Booking_ID"),
        "bookings",
        "Apartamentos",
        ["Booking ID"],
        ["Booking ID"],
        onupdate="CASCADE",
    )
    op.create_index(op.f("ID"), "bookings", ["ID"], unique=True)
    op.alter_column(
        "bookings", "Nombre,Apellidos", existing_type=mysql.VARCHAR(length=100), nullable=False
    )
    op.drop_column("bookings", "Notes")
    # ### end Alembic commands ###
